"""Add evidence fields

Revision ID: 05dad2c2d938
Revises: db53150cc2c9
Create Date: 2025-11-21 12:37:59.061060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05dad2c2d938'
down_revision: Union[str, None] = 'db53150cc2c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('evidence', sa.JSON(), nullable=True))
    op.add_column('chunks', sa.Column('entities', sa.JSON(), nullable=True))
    op.add_column('chunks', sa.Column('events', sa.JSON(), nullable=True))
    op.add_column('chunks', sa.Column('facts', sa.JSON(), nullable=True))
    op.add_column('chunks', sa.Column('SLG', sa.JSON(), nullable=True))
    op.add_column('chunks', sa.Column('section_detection', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'section_detection')
    op.drop_column('chunks', 'SLG')
    op.drop_column('chunks', 'facts')
    op.drop_column('chunks', 'events')
    op.drop_column('chunks', 'entities')
    op.drop_column('chunks', 'evidence')
    # ### end Alembic commands ###
